services:
  trino-coordinator:
    image: trino/trino:476
    container_name: trino-coordinator
    ports:
      - "8080:8080"
    volumes: 
      - "/m_laketop/trino/coordinator/config.properties:/etc/trino/config.properties"
      - "/m_laketop/trino/catalog:/etc/trino/catalog"
      - "/m_laketop/trino/coordinator/init.sql:/etc/trino/init.sql"
  trino-worker-1:
    image: trinodb/trino:476
    container_name: trino-worker-1
    volumes:
      - "/m_laketop/trino/worker/config.properties:/etc/trino/config.properties"
      - "/m_laketop/trino/catalog:/etc/trino/catalog"
    depends_on:
      - trino-coordinator
  trino-worker-2:
    image: trinodb/trino:476
    container_name: trino-worker-2
    volumes:
      - "/m_laketop/trino/worker/config.properties:/etc/trino/config.properties"
      - "/m_laketop/trino/catalog:/etc/trino/catalog"
    depends_on:
      - trino-coordinator
